apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sample1
  namespace: mojtaba-ahmadi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-sample1
  template:
    metadata:
      labels:
        app: nginx-sample1
    spec:
      containers:
      - name: nginx-sample1
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
